# Generated by Django 5.1.2 on 2024-11-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
