# Generated by Django 5.1.2 on 2024-10-30 12:37

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=products.models.generate_sku, max_length=250, unique=True),
        ),
    ]
